### PR TITLE
deal with safari bug Leaflet version 1.7

### PR DESCRIPTION
**Pull request by hupe13**
This solves a bug in Leaflet 1.7.1: https://wordpress.org/support/topic/marker-info-not-displayed-with-safari-browser/

### CODE REVIEW

**Comment by Raruto** [comment]
Hi hupe,

please submit a separate pull request for the other issue you reported: https://github.com/Raruto/leaflet-gesture-handling/issues/14#issue-1228927528

> - To make [L.control.layers](https://leafletjs.com/examples/layers-control/) and [Leaflet.Control.Opacity](https://github.com/dayjournal/Leaflet.Control.Opacity) work together with gesture handling, I have made the following changes: https://github.com/hupe13/extensions-leaflet-map-github/blob/bb532555d4fbf0687e964f8847a393d9fa75e5f3/leaflet-plugins/leaflet-gesture-handling-1.4.1/leaflet-gesture-handling-leafext.js#L205-L217 . Without these changes it is difficult to operate the control fields on touch devices.

_Have a nice day,
Raruto_

**Comment by Raruto** [comment]
If this has already been solved within the leaflet I would avoid handling it here (also because it is code I did not understand exactly what it does..), anyway, simplifying it further, I think that condition should be more or less as follows:

```js
_enableInteractions: function() {
  this._map.dragging.enable();
  this._map.scrollWheelZoom.enable();
  if (this._map.tap) this._map.tap.enable();

  // Fix: https://github.com/Leaflet/Leaflet/issues/7255
  if (L.Browser.safari && L.version < "1.8") this._map.tap.disable();
},
```

_Raruto_

**Comment by hupe13** [comment]
>  I did not understand exactly what it does.

<s>I will send you a picture with the problem on Safari on Monday.</s>
I found the explanation: https://github.com/bozdoz/wp-plugin-leaflet-map/issues/156
The problem is solved in Leaflet 1.7.1 if you set "tap" in Safari to false.

**Comment by Raruto** [comment]
@hupe13 check out this other pull https://github.com/Raruto/leaflet-gesture-handling/pull/18, maybe is more suited to the problem you are reporting.

**Pull request closed without merging**
